#!/usr/bin/env bash
#  configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Holberton School" | sudo tee /var/www/html/index.ngix-debian.html
sudo sed -i "/listen 80 default_server/a/add_header X-Served-By\"$HOSTNAME\";"/etc/nginx/sites-available/default
sudo service nginx start
