#!/usr/bin/env bash
#Bash script that gives you information about the holbertonschool file.

i=holbertonschool
if [ -e "$i" ]
then
    echo "holbertonschool file exists"
    if [ -s "$i" ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -i "$f" ]
    then
        "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi