#!/usr/bin/env bash
# Changes the IP addresses of localhost and facebook.com


cp /etc/hosts ~/hosts.new
sed -i s/^172.*$// ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
